### ISSUE TITLE
Calydon light with highlight_line set to true

### ISSUE THREAD

**Issue by sigod** [carlcalderon/sublime-color-schemes#5]
`highlight_line: true` and Calydon light don't go well together:

![image](https://user-images.githubusercontent.com/1175750/56453676-8fa40200-634e-11e9-81ab-06a253d770e8.png)

**Comment by carlcalderon** [comment]
You are absolutely right @sigod. We've got a few options here. I think it's obvious that option 4 is the right way to go but it will invert the current behavior which is not ideal either. Let me know what you think and I'll ask some people I know too.

These are ways to approach, _not_ the suggested final color.

**1** Even darker
![option1](https://user-images.githubusercontent.com/424665/56455449-bcf8ac00-635e-11e9-826c-c93e4c431ee7.png)

**2** A bit lighter
![option2](https://user-images.githubusercontent.com/424665/56455450-bcf8ac00-635e-11e9-9fd0-d8f2bd078960.png)

**3** Much lighter
![option3](https://user-images.githubusercontent.com/424665/56455451-bd914280-635e-11e9-9643-6015d4a0fb99.png)

**4** Almost white
![option4](https://user-images.githubusercontent.com/424665/56455452-bd914280-635e-11e9-8e56-c771a107b713.png)

**Comment by sigod** [comment]
How about tweaking the color of identifiers? Even without highlighting it's a bit hard to distinguish the identifiers for me.

**Comment by sigod** [comment]
I think option 1 can be great, only it could introduce the same issue for black text and dark background. And I think option 4 could be excellent if identifiers are darkened a bit.

**Comment by carlcalderon** [comment]
Thank you @sigod for your input!

Tricky. I'll have to experiment a bit more with this. The identifiers are too bright but darkening might make it hard to distinguish identifiers from strings.

**Comment by carlcalderon** [comment]
The `highlight_line` color is not specified in the Calydon Light theme. Users will have individually defined highlight colors (or generated from the theme). Since this is a light theme, I assume the highlight will be fairly light as well. For now, I have increased the contrast of the actual issue; `Library function` instead (https://github.com/carlcalderon/sublime-color-schemes/commit/828e8365f18f2dc11bb6bc1b3335ba20808e71cf).

This should solve this issue for most people and not be a too noticeable change for others.
